previous update to the code due to changes in lombok.patcher introduced a bug, which was causing the following exception in the eclipse error log:
java.lang.VerifyError: (class: org/eclipse/jdt/internal/corext/dom/LinkedNodeFinder, method: findByBinding signature: (Lorg/eclipse/jdt/core/dom/ASTNode;Lorg/eclipse/jdt/core/dom/IBinding;)[Lorg/eclipse/jdt/core/dom/SimpleName;) Incompatible argument to function